### ISSUE TITLE
#109685: "Game does not begin if started in real-time mode"

### ISSUE THREAD

**Issue by joesimpson** [joesimpson/bga-flipfreighters#12]
https://boardgamearena.com/bug?id=109685

> I have only tested this in solo mode, but if you begin a game in real-time mode, when the game loads no cards are drawn and the control banner at the top simply shows "Start turn" with no buttons visible. The only way to play the game at this point is to go to options and change to turn-based.

Erreur au replay de sa partie : 
```
ly_studio.js:1 During notification newTurn
Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at Object.resetOvertimeHourOnCard (https://x.boardgamearena.net/data/themereleases/current/games/flipfreighters/231214-1629/flipfreighters.js:1:36814)
    at https://x.boardgamearena.net/data/themereleases/231214-1001/js/dojoroot/dojo/dojo.js:1:23207
    at forEach (https://x.boardgamearena.net/data/themereleases/231214-1001/js/dojoroot/dojo/dojo.js:1:25247)
    at Array.forEach (https://x.boardgamearena.net/data/themereleases/231214-1001/js/dojoroot/dojo/dojo.js:1:79696)
    at Object.notif_newTurn (https://x.boardgamearena.net/data/themereleases/current/games/flipfreighters/231214-1629/flipfreighters.js:1:52195)
```

ce qui correspond à resetOvertimeHourOnCard: function :  `t.setAttribute("data_suit", this.dayCards[s].type)` (code fixe depuis 2 mois) mais ici `this.dayCards` vaut []
car au chargement de la page il n'y a pas de dayCards 
`Starting game setup`
car le state est toujours "stNewTurn"
```
round_number: "0"
turn_number: "0"
```

**Comment by joesimpson** [comment]
Je ne reproduis pas sur une partie temps reel chez moi https://boardgamearena.com/archive/replay/231214-1001/?table=458613112&player=87163447&comments=87163447;

**Comment by joesimpson** [comment]
Reproduit direct avec le waiting screen en dev (meme en tour par tour) : [https://studio.boardgamearena.com?studioLockingDuration=10](https://studio.boardgamearena.com/?studioLockingDuration=10)

https://studio.boardgamearena.com/1/flipfreighters?table=545685

```
 During notification newTurn
this.dayCards[row] is undefined
resetOvertimeHourOnCard@flipfreighters.js:1712:17
```

**Comment by joesimpson** [comment]
Deployed in today version 240106-1850
